///
/// @Generated by Mockolo
///



import Foundation
import ObjectMapper
import RxSwift
@testable import NFTCollection


final class AssetsLoadableMock: AssetsLoadable {
    init() { }


    private(set) var loadAssetsCallCount = 0
    var loadAssetsHandler: ((Bool) -> (Single<AssetsResult>))?
    func loadAssets(loadMore: Bool) -> Single<AssetsResult> {
        loadAssetsCallCount += 1
        if let loadAssetsHandler = loadAssetsHandler {
            return loadAssetsHandler(loadMore)
        }
        fatalError("loadAssetsHandler returns can't have a default value thus its handler must be set")
    }
}

